#index:
#    path: /
#    controller: App\Controller\DefaultController::index

# the "app_lucky_number" route name is not important yet
app_jsonlines_read:
  path: /jsonlines/read
  controller: App\Controller\JsonLinesController::number
